p catch(:foo) {
  throw :foo, 'returned value'
}